[package]
name = "html2maud"
version = "0.1.9"
edition = "2021"
readme = "../Readme.md"
description = "html2maud is a library / cli to convert html to maud template code"
repository = "https://github.com/grayfallstown/html2maud"
license = "MIT OR Apache-2.0"
keywords = ["maud", "html", "template"]
categories = ["command-line-utilities", "development-tools"]

[lib]

[dependencies]
tl = "0.7.7"
regex = "1.10.2"
